### ISSUE TITLE
Displaying the uploaded file in the browser.

### ISSUE THREAD

**Issue by pythonl1** [axelpale/minimal-django-file-upload-example#14]
Hi, 

I am fairly new to python and django and I was hoping that you can provide me with an example for displaying the uploaded file in the browser along with other metadata related that particular file.

Thanks

**Comment by axelpale** [comment]
Hi! Unfortunately I do not posess the time to answer your question deeply. Also I think this is not an *issue* of the project and thus I will close the issue.

However, the project currently shows a link to the file i.e. you know the URL. Therefore, in the case of image upload, you could just put the URL inside `<img>` tag. Also, by using the docfile (instance of FileField) of Document model, you have an access to the filepath and with the filepath you can use tools provided by the python to dig up some metadata, [for example](http://stackoverflow.com/questions/2104080/how-to-check-file-size-in-python):

    import os
    filesize = os.path.getsize("/path/myfile.png")

Maybe this will help. Happy learning!

**Comment by pythonl1** [comment]
No worries. Thanks for the help!
