### ISSUE TITLE
environment Path is fixed.. cant execute another django project 

### ISSUE THREAD

**Issue by kesava5253** [axelpale/minimal-django-file-upload-example#19]
Executed the file , minimal-django-file-upload-example/src/for_django_1-9/myproject    Using **python manage.py runserver** all executed fine , but when i tried to another project of mine , path not changing ..  plzz help me with solution.

>> I am a Beginner to Django <<

**Comment by axelpale** [comment]
I'm sorry but there is too little information to describe the issue.. and I have been lazy and kept this issue without an answer for two years! Maybe it is time to close this for now....
