### ISSUE TITLE
HTML Templates?

### ISSUE THREAD

**Issue by michaelyan-coupa** [axelpale/minimal-django-file-upload-example#23]
Hi, are there any other HTML templates for this project other than the original? Thanks!

**Comment by axelpale** [comment]
Hi. There are no pre-made templates as far as I know. Layout and styling are not goals of the project. The project aims to provide a starting point where you can begin to build your app, including the templates.

Do you feel the project needs additional HTML templates or does the current template miss some important features? If so, please explain, I would like to hear if there is something to improve.

**Comment by axelpale** [comment]
Almost a month has gone and no answers to this. I will close the issue.
