### ISSUE TITLE
How to load an image from cdn path in django

### ISSUE THREAD

**Issue by sandhyalaxmiK** [axelpale/minimal-django-file-upload-example#26]
Hi i have created a file field. Now i want to browse a file(image) from cdn path. How to do it??

**Comment by axelpale** [comment]
Hi. What do you mean by browsing a file? Do you want to upload an image from CDN URL or publish the image to CDN? I am afraid both options are out of scope of this minimal example.

**Comment by axelpale** [comment]
I will need to close this issue for now. If you have any further details within the scope of the project, I can open it again.
