### ISSUE TITLE
Request - Log status for upload process

### ISSUE THREAD

**Issue by schults** [axelpale/minimal-django-file-upload-example#28]
Hey guys, is it possible to add some kind of log if, for example, the upload fails for some reason during the upload process?

**Comment by axelpale** [comment]
Hi! Thanks for the suggestion. The purpose of the project is to provide a minimal set of features necessary to implement file uploading. The minimal set is intended to be those features that every upload-enabled Django project needs and nothing more. Non-essential features like the failure log, although useful in many cases, would make it harder for first-timers to distinguish the essential from non-essential and therefore do not support the purpose of the project.

However, what we could do, as such feature is truly useful in many cases, is to extend the README with a list of features that users should consider beyond the minimal features.

Therefore, if you know or stumble upon a good source that either implements or discusses the upload failure log, I would happily create such what-to-consider-next kind of list and add your preferred source to it.

I am closing the issue but feel free to express your additional thoughts.
