### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by leosamu** [axelpale/minimal-django-file-upload-example#8]
Where you wrote 
myapp/urls.py: changed from django.conf.urls import patterns, url to from django.conf.urls.defaults import patterns, url
i think is just the other way around
myapp/urls.py: changed from django.conf.urls.defaults import patterns, url  to from django.conf.urls import patterns, url

**Comment by axelpale** [comment]
Thanks Leo! It took me a while to look into this but you were right and now the order is swiched.
